Added devices API
erickt/rust-zmq pull request #331
Opened 2021-03-06 04:44 UTC by drbh

added the devices api to match functionality in [pyzmq](https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/devices/devices.html)

I tried to follow the style of the library - please let me know if there are any changes needed before merging

2021-06-28 07:11 UTC, tdudz commented
any updates on this? would like to see it get merged

2021-08-05 21:00 UTC, tdudz commented
bump on this again, thanks

2021-08-05 21:44 UTC, drbh commented
@erickt, any update on reviewing/merging this? Thanks

2021-08-09 16:05 UTC, erickt requested changes

2021-08-09 16:05 UTC, erickt commented on src/lib.rs
> +    }
Could this return a result rather than a panic?

Also, could you add a newline before this line?

2021-08-14 19:06 UTC, erickt requested changes
Looking through the [pyzmq API docs](https://pyzmq.readthedocs.io/en/latest/api/zmq.devices.html), it looks like the device api was dropped in ZMQ 3.2, and replaced with http://api.zeromq.org/master:zmq-proxy. We do already have support for this in https://github.com/erickt/rust-zmq/blob/eede4315e10eccddec4348561c42ded534e6001e/src/lib.rs#L1138.

I wouldn't consider myself the main maintainer of this library (cc @rotty), but it looks like we're currently depending on zeromq 4.1 and above, so could you switch to `proxy`? 

Also, do you know if zmq 4.1 and above actually exposes `zmq_device`? It might not actually be exposed, which might cause a compilation issue.

Finally, if we do decide to support this device API, can you add some tests for it?

2021-08-14 19:13 UTC, tdudz commented
ah ok i didn't see that device was deprecated. ill try switching over to proxy, thanks

2021-08-14 19:15 UTC, erickt commented
@tdudz no problem! Please let me know if you still need this functionality, and we can try to come up with a way to implement it (since it seems pyzmq somehow does it)

2021-08-15 03:38 UTC, tdudz commented
@erickt i just tested my project using proxy and it seems to work fine. sorry for all the trouble, i should have read the docs a little closer! appreciate the help though and thanks for the great zmq package

2026-04-17 17:23 UTC, drbh commented
closing since original changes targeted deprecated apis and this pr is old/stale. thanks for the original review

2026-04-17 17:23 UTC, closed without merging